
class Prompt:
    @staticmethod
    def item_screen_summarise(package, current_screen_xml, activity):

        return "Q:CURRENT_ACTIVITY_NAME: " + activity + ". XML: " + current_screen_xml + ". PACKAGE: "+ package+".\n";
    
    @staticmethod
    def screen_summarise(package, current_screen_xml, activity):
        rule = 'Input current screen information, including CURRENT_ACTIVITY_NAME: current that user is on, XML: Current Android UI element on the screen as XML code, PACKAGE: package name of Android app. Output the summarisation (description) for this screen.\n'       
        current_screen_xml1 = '<node id="3656" class="View" /><node id="3657" class="TextView" text="Track"  /><node><node id="3659" class="Button" text="ADD" clickable="true" bounds="[904,77][1036,209]" /></node><node/><node id="3661" class="ImageView" resource-name="parcelImage" clickable="true" bounds="[333,550][746,963]" /><node id="3662" class="TextView" text="Don’t miss a delivery – get your parcels &#10;where y" bounds="[66,1382][1014,1478]" /><node id="3663" class="Button" text="Log in" clickable="true" bounds="[66,1544][1014,1654]" /><node id="3664" class="Button" text="Sign up for free" clickable="true" bounds="[66,1676][1014,1786]" /><node id="3665" class="ImageView" resource-name="navigation_bar_item_icon_view" /><node id="3666" class="TextView" text="Track" " /><node id="3668" class="TextView" text="Find us" bounds="[348,1965][462,2009]" /><node id="3669" class="ImageView" bounds="[642,1896][708,1962]" /><node id="3670" class="TextView" text="Account" /><node id="3672" class="TextView" text="More" /><node id="3673" class="View" /><node /></node>'
        current_screen_xml2 = '<node id="3249" class="TextView" text="Uber One&#10;A$9.99/mo 2 weeks free" /><node id="3253" class="TextView" text="$0 Delivery Fee on eligible orders $20+ (Service " /><node id="3257" class="TextView" text="Member savings on rides (at least 10% off) and to" /><node id="3261" class="TextView" text="Exclusive Member Perks like promotions and experi" /><node id="3265" class="TextView" text="$5 credit if the Latest Arrival estimate on your " /><node id="3269" class="TextView" text="Cancel anytime without additional fees" bounds="[176,1354][1036,1409]" /><node id="3271" class="TextView" text="Members save around  A$30 every month" /><node id="1" class="TextView" text="Based on average monthly savings of members in yo" /><node id="2" class="Button" text="Join Uber One" clickable="true" bounds="[44,1676][1036,1830]" />node id="3275" class="TextView" text="Home" /><node id="4" class="TextView" text="Browse"/><node id="3278" class="TextView" text="2" /><node id="3282" class="TextView" text="Account" /><node id="3284" class="TextView" text="Uber One" /></node>'
        current_screen_xml3 = '<node id="3757" class="ScrollView" resource-name="main_coordinator" scrollable="true" bounds="[0,66][1080,1808]"><node><node id="3758" class="ImageButton" tooltip-desc="Show navigation menu" content-desc="Show navigation menu" clickable="true" bounds="[0,77][154,231]" /><node id="3759" class="ImageView" /><node id="3760" class="TextView" text="Files" /><node id="3762" class="ImageView" clickable="true" bounds="[0,424][1080,974]" /><node id="3763" class="TextView" text="Nearby Share" /><node id="3764" class="Button" text="Send" clickable="true" /><node id="3765" class="Button" text="Receive" clickable="true" bounds="[525,1106][818,1238]" /><node id="3766" class="ImageView" /><node id="3767" class="TextView" text="Using Nearby Share" /></node><node id="3769" class="ImageView" resource-name="navigation_bar_item_icon_view" bounds="[147,1852][213,1918]" /><node id="3770" class="TextView" text="Clean" bounds="[134,1947][225,1994]" /><node id="3773" class="TextView" text="Browse" /><node id="3776" class="TextView" text="Nearby Share" /><node /></node>'

        example1 = Prompt.item_screen_summarise('au.com.android.auspost', current_screen_xml1,".feature.track.TrackActivity" ) + 'A: This is the screen for tracking orders in AusPost app, include a button to add new track item. In addition, user can log in and sign up from this screen.\n'
        example2 = Prompt.item_screen_summarise('com.ubercab.eats', current_screen_xml2, '.core.activity.RootActivity') + 'A: This is the screen for Uber One in Uber Eats, include a button to join Uber One.\n'
        example3 = Prompt.item_screen_summarise('com.google.android.apps.nbu.files', current_screen_xml3, '.home.HomeActivity') + 'A: This is the nearby share page in Files app, with send and receive button on the screen to share or receive files.\n'

        return rule + example1 + example2 + example3 + Prompt.item_screen_summarise(package, current_screen_xml, activity) + "A:"